site_name: EXPOSICIÓN
dev_addr: 127.0.0.1:8001
# site_url: 
# repo_url: 
# repo_name: <i class="fa fa-git"></i>

theme:
    name: mkdocs
    custom_dir: resources/
extra_css:
    - css/page.css
nav:
    - Colaborativas:
        - Tema : prueba.md
    - EJEMPLOS:
        - Ejemplo: prueba2.md
copyright: ©GMDXX
site_author: GMDXX
